### ISSUE TITLE
Color Picker Card

### ISSUE THREAD

**Issue by elliotmatson** [ayushsharma82/ESP-DASH#192]
**Is your feature request related to a problem? Please describe.**
I'm working on a tally light solution, that triggers certain lighting states based on the state of network devices, and it would be really helpful to have a color picker available!

**Describe alternatives you've considered**
Currently I'm just using a text field that can accept color strings or hex values, but that isn't as clean

**Comment by ayushsharma82** [comment]
Added in pipeline. I'll update when it's implemented.


I'll need some more info:
  1. What is more convenient: `hex` string or `rgb`/`rgba` values? 
  2. Is alpha channel necessary?

**Comment by elliotmatson** [comment]
Thanks! No need for alpha, and hex would probably be better

**Comment by mathieucarbou** [comment]
For what is worth, if this feature gets implemented, I would like to see activated with a macros, like `DASH_COLOR_PICKER_SUPPORT`, in order to avoid increasing too much the PROGMEM data.
Note: I am taking as an hypothesis that adding this feature would require subsequent code of additional the javascript, css and  and html.

**Comment by finchamp** [comment]
Bootstrap has a color picker, and there are a number of other freeware JS
options out there. I'm hoping it would be pretty simple to implement, but I
can't say.

**Comment by elliotmatson** [comment]
Looks like this is completed in the latest Pro release, right? Thanks so much, looking forward to testing it!
