### ISSUE TITLE
Combination of Toggle Button and Slider Card

### ISSUE THREAD

**Issue by mhummels** [ayushsharma82/ESP-DASH#209]
I am using ESP-DASH for my smart van project and bought Pro today. Thank you for the great work and quick support getting the Pro download working.

As I have some dimmable lights in my van, it would be really nice to have a combination of the slider card with the toggle button card. Just imagine you would be able to just press on the icon of the slider card to toggle the light on and off and have the slider for the brightness right next to it. Currently I have to use two different cards to get the same result. It works, but it is a little inconvenient.

**Comment by mathieucarbou** [comment]
That's a good idea that I would also be interested to have on my project. I also dim some load and I have a toggle button and a slider currently to provide a quick toggle at full power and and a power control. It would be nice  indeed to have sort of toggle dimmer that would integrate the button in the icon.

Also, this is just a UI change, no code change, because level == 0 (min value) means button off and level == 100 (max) means button  on.

Note that if you have the pro version you can create your own cards ;-)

**Comment by mhummels** [comment]
> Note that if you have the pro version you can create your own cards ;-)

Is that documented somewhere? I checked the code and found only precompiled HTML. For my understanding I would need to adjust that to be able to add a custom card as the JSON just defines the types but not the UI or am I wrong?

**Comment by mathieucarbou** [comment]
> I checked the code and found only precompiled HTML.

If you bought the Pro version, you also have the portal code and can modify it (after reading the README).

That's how i was able to develop all the latest contributions I did, that you guys now also have in the Pro version ;-)

**Comment by mathieucarbou** [comment]
@ayushsharma82 : the stale bot is marking as stale a lot of issues that are not issues but feature requests from the community, which cannot be acted upon because the source code is not available. Stale bot is used to mark issues or support tickets that are left abandoned without any activity for a while. Closing community or customer feature requests, which is a way to capture the user's requirements to plan further development, is IMO not suited to stale bot.
