### ISSUE TITLE
Publish sources  of the "dash_webpage"

### ISSUE THREAD

**Issue by dkaukov** [ayushsharma82/ESP-DASH#233]
**Describe the bug**
Hi, could you please publish sources of the Vue frontend. Currently it is provided in the compiled form here https://github.com/ayushsharma82/ESP-DASH/blob/master/src/dash_webpage.cpp

**Comment by ayushsharma82** [comment]
UI source is only available with Pro version. Feel free to purchase the pro version to access it.

**Comment by dkaukov** [comment]
The GPL requires that whenever you distribute a compiled binary (a "blob"), you must also make the corresponding source code available under the same GPL license. This ensures that recipients of the binary can study, modify, and redistribute the software just as they could with the original source code.

**Comment by ayushsharma82** [comment]
@dkaukov When we release software under GPL-3.0, we are choosing to apply the terms of the GPL-3.0 to the software for anyone who "receives" it.

The author is not bound by these terms themselves—they can license the software under different terms or dual-license it under multiple licenses.

**Comment by dkaukov** [comment]
@ayushsharma82 you are distributing your software  through various channels: GitHub, PlatformIO Registry, etc..  For Distribution Under GPL-3.0, the author must provide the source code for any compiled binaries they distribute under the GPL-3.0 license.

**Comment by dkaukov** [comment]
@ayushsharma82, could you please re-open this ticket, so everyone can participate in our discussion.

**Comment by mathieucarbou** [comment]
> @ayushsharma82 you are distributing your software through various channels: GitHub, PlatformIO Registry, etc.. For Distribution Under GPL-3.0, the author must provide the source code for any compiled binaries they distribute under the GPL-3.0 license.

Can you please show us where you (mis)read that in the license ?

@ayushsharma82 is the author and copyright owner: whatever he releases under GPL, this is up to the  licensee (you), not the licensor (owner), to comply to the license. The file you are talking about, however it was built, is his code that he provides to you.

You could post your question to gnu@gnu.org, asking them to add this case in their FAQ if not already there (https://www.gnu.org/licenses/gpl-faq.html).

**Comment by dkaukov** [comment]
@mathieucarbou See section 6: https://github.com/ayushsharma82/ESP-DASH/blob/master/LICENSE#L245. This ensures that recipients of the binary can study, modify, and redistribute the software just as they could with the original source code.

**Comment by mathieucarbou** [comment]
> @mathieucarbou See section 6: https://github.com/ayushsharma82/ESP-DASH/blob/master/LICENSE#L245. This ensures that recipients of the binary can study, modify, and redistribute the software just as they could with the original source code.

You are mixing "The Program" with the "covered work" and you might need to read the definitions of the terms especially what "convey" means.

**Comment by ayushsharma82** [comment]
@dkaukov

Let's say even if your words are true, I can also sit here and waste time to debate whether it can be called a binary or not because dash_webpage.cpp in itself is "source code" which is readily available to study, modify, and redistribute in clear text. 😄

To add to point of @mathieucarbou , Read what's in between these lines: https://github.com/ayushsharma82/ESP-DASH/blob/master/LICENSE#L81C11-L81C47

**Comment by dkaukov** [comment]
Hi, @ayushsharma82.
The [dash_webpage.cpp](https://github.com/ayushsharma82/ESP-DASH/blob/master/src/dash_webpage.cpp) is "[Binary blob](https://en.wikipedia.org/wiki/Binary_blob)"  which cannot be covered by GPL.  Hence it should be removed from this distribution or licence should be changed. For example, you can direct users to download "dash_webpage.cpp" from your website where you can clearly state how your company guaranty security and what Liability and Warranty it provides.

**Comment by mhaberler** [comment]
@dkaukov I have a proposal for you:

Write and publish an alternative to this repo with the license of your dreams.

**Comment by mathieucarbou** [comment]
@ayushsharma82 : just added in https://github.com/platformio/platformio-registry/issues/105#issuecomment-2288437945 some clarifications over this file and how it comes from because what @dkaukov is considering as source is actually not sources but a binary output from another project (however this output is generated or sourced from it does not matter - this is a project binary output so as per the GPL FAQ not covered by the projet's GPL license apparently. Only the sources of this project are)

**Comment by mathieucarbou** [comment]
> Could you please provide more details about the source of this binary and how its licensing aligns with the GPL-3.0? I believe this would help clear up any misunderstandings and ensure the project is fully compliant with the open-source license.

This is a question for @ayushsharma82 , not me. 

The output is build from a set of nom dependencies that all have MIT license.

That is definitely something @ayushsharma82 might add to his website for clarity.

I too working an organization where we have to list all the dependencies of projects, even dependencies of dependencies, even nom ones, their website, license, name,next.

So yes this would be nice to list the dependencies used and their website and license so that people can know that this generated output comes from MIT librairies.

For the other comments you have, please send an email to the gnu   foundation. You are not a lawyer or part of gnu so what you *think* does not have any value in this discussion.

License matters like that should be processed by experts, not developers.

**Comment by dkaukov** [comment]
To ensure that all aspects of this issue are thoroughly reviewed and to protect the integrity of the project, I have filed a report with the relevant authorities, including PlatformIO and the GNU Project. My intention is to seek clarification on how the GPL-3.0 applies in this case and to ensure that the project fully complies with its licensing obligations.

I appreciate the effort to clarify the situation, and I hope this process will lead to a better understanding for everyone involved.

**Comment by ayushsharma82** [comment]
As we speak, dkaukov’s account is banned from accessing my repositories or take part in this discussion. The constant nagging, speculation and unprofessional baseless claims are not acceptable by me or anybody part of this project, these comments only promote hate while he passive aggressively promotes it.
