### ISSUE TITLE
Link Card - open new window but with ESP-DASH again

### ISSUE THREAD

**Issue by CByteITSolution** [ayushsharma82/ESP-DASH#238]
Link not work.
when I press the button an new window in the browser open but again with the ESP IP address 
and ESP-DASH and not the link I set in setup with example
_card_link_webserial.update("https://espdash.pro");_

**Comment by mathieucarbou** [comment]
Hello,
I am the author of this extension (which I contributed to the pro version). I am using them a lot and they do work.
I am using them like this:

```c++
Card _consoleLink = Card(&dashboard, LINK_CARD, YASOLR_LBL_084);
```

then, called only once because link does not change for me:

```c++
_consoleLink.update("/console");
```

The console page opens in a new window.

You can look at the page html source to see how it is generated: this is a simple href link with a target set to _blank.

Is your browser preventing opening in new window or tab ?

**Comment by CByteITSolution** [comment]
Hello, 
works with:

card_link_otaupdate.update("http://" + strIP + ":8081/update"); 

thx
