### ISSUE TITLE
Possibility to modify / extend static information

### ISSUE THREAD

**Issue by qroac** [ayushsharma82/ESP-DASH#83]
I just switched from ESP-UI to ESP-Dash and I really like it.
Thank you for the great work

I intend to use it on multiple microcontrollers in the same network, with quite simmilar set of cards.
So having multiple dashes opened in different tabs, its hard to determine which is which.

I would love to:
- be able to change title tag and page title from "DASH" to something different
- have a kind of subtitle displayed under or beside the title for a short description
- have a section on the info page to add a own description or short device documentation
- add "system" measurements as additional lines to the stats page and thus keep the main dashboard clean for core device functionality  
e.g. water level measurement, flow control and valve status on the dashboard, VCC, temperature and humidity as lines on the stats page

**Comment by ayushsharma82** [comment]
Those are some great suggestions! I'll add them to our project plan for V3. Thanks!

**Comment by DaeMonSx** [comment]
good idea 👍

**Comment by logowe** [comment]
@ayushsharma82 
Just had a look at dash. 
Like @qroac I have a similar scenario for my applications (3 different parties Heating Control System in the same house). I intend to offer this next year to 'real' customers if it passes the ongoing test phase (heating is off due to in the northern hemisphere).
I have created the Web GUI using HTML with embedded CSS and JS. But this is a hard-to-maintain aproach!
dash could be the ulitmate simplest solution if all the "branding" could be changed to use mine - could ...
You promised V3 would have thic features but I had a look in V4 and the maybe not updated documentation and did not find anything. 
Am I looking in the wrong places?
Please help,

**Comment by ayushsharma82** [comment]
@logowe I wasn't available to fit those features in v3 with my limited time. Right now this open source version is in LTS ( long term support ) mode so any new features will only be added in V4 pro which should be available in a month or so if everything works smoothly.

I'm keeping this issue open so that I can keep track of features which people want.

**Comment by ayushsharma82** [comment]
@qroac  It has been some time but thanks for the nice suggestions! Almost all are added in V4 and V4 Pro including Statistics, custom logo, custom title.

Closing this issue satisfactorily now.
